# Generated by Django 5.1.1 on 2024-10-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('workplace', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img_url', models.TextField()),
                ('deletion_flag', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'speakers',
            },
        ),
    ]
