# Generated by Django 5.1.1 on 2024-10-29 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('workplace', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('img_url', models.TextField(blank=True)),
                ('deletion_flag', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'speakers',
            },
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(blank=True)),
                ('resolve_date', models.DateTimeField(blank=True)),
                ('topic', models.TextField(blank=True)),
                ('meetup_date', models.DateTimeField(blank=True)),
                ('moderator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderator_action', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetups',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approx_perfomance_duration', models.IntegerField(blank=True)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speakers.meetup')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speakers.speaker')),
            ],
            options={
                'db_table': 'invites',
                'constraints': [models.UniqueConstraint(fields=('speaker', 'meetup'), name='UQ_Invites_speaker_id_and_meetup_id')],
            },
        ),
    ]
