# Generated by Django 5.1.1 on 2024-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_alter_invite_approx_perfomance_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='viewers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
