# Generated by Django 5.1.1 on 2025-02-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
